### ISSUE TITLE
Критичный неправильный перевод на русский язык

### ISSUE THREAD

**Issue by knl97vladimir** [MicrosoftDocs/xamarin-docs.ru-ru#11]
Чтение ресурсов
Ресурсы считываются с помощью ассетманажер.

Связанные ссылки
ассетманажер
Локального

Необходимо заменить на:
AssetManager
Context

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: d4929345-b389-d55d-5fad-dbd429211541
* Version Independent ID: 33946e4b-4f22-b2f8-8965-a3399beec41e
* Content: [Использование ресурсов Android - Xamarin](https://docs.microsoft.com/ru-ru/xamarin/android/app-fundamentals/resources-in-android/android-assets?tabs=windows#feedback)
* Content Source: [docs/android/app-fundamentals/resources-in-android/android-assets.md](https://github.com/MicrosoftDocs/xamarin-docs.ru-ru/blob/live/docs/android/app-fundamentals/resources-in-android/android-assets.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by srvbpigh** [comment]
Hello, @knl97vladimir
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Здравствуйте, @knl97vladimir
Спасибо за отзыв. 
Наши лингвисты рассмотрели Ваши предложения и приняли их. Мы внедрили Ваши правки в обновленные статьи на сайте документации, опубликованные на следующих страницах: https://docs.microsoft.com/ru-ru/xamarin/android/app-fundamentals/resources-in-android/android-assets?tabs=windows#feedback
Мы очень ценим Ваш вклад в наши статьи и будем рады получить другие полезные отзывы. 
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт
