### ISSUE TITLE
Incorrect russian localization

### ISSUE THREAD

**Issue by Normandy** [MicrosoftDocs/xamarin-docs.ru-ru#13]
Таблевиев -&gt; Table View
ентрицелл -&gt; EntryCell

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 7ad16e14-5abd-7115-a64a-69db1178d58a
* Version Independent ID: 1602a6ea-3968-006b-9d63-63c25051b5b4
* Content: [Таблевиев Xamarin. Forms - Xamarin](https://docs.microsoft.com/ru-ru/xamarin/xamarin-forms/user-interface/tableview#feedback)
* Content Source: [docs/xamarin-forms/user-interface/tableview.md](https://github.com/MicrosoftDocs/xamarin-docs.ru-ru/blob/live/docs/xamarin-forms/user-interface/tableview.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by FoggyFinder** [comment]
Related: #12 

I don't think it will be fixed anyway.

**Comment by Normandy** [comment]
Ok, thx for answer
