### ISSUE TITLE
Не рабочий код

### ISSUE THREAD

**Issue by Metalstyle** [MicrosoftDocs/xamarin-docs.ru-ru#14]
https://youtu.be/bYlOvAThnDs

Видео о том, что код на страничке нерабочий.

var assembly = IntrospectionExtensions.GetTypeInfo(typeof(LoadResourceText)).Assembly;
Stream stream = assembly.GetManifestResourceStream("WorkingWithFiles.LibTextResource.txt");
string text = "";
using (var reader = new System.IO.StreamReader (stream))
{  
    text = reader.ReadToEnd ();
}

Не работает.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 51f9e390-1b2e-fe0b-3969-8feb203d9fb8
* Version Independent ID: 714d5991-0577-4d86-3585-bed8788e73cf
* Content: [Обработка файлов в Xamarin.Forms - Xamarin](https://docs.microsoft.com/ru-ru/xamarin/xamarin-forms/data-cloud/data/files?tabs=windows#feedback)
* Content Source: [docs/xamarin-forms/data-cloud/data/files.md](https://github.com/MicrosoftDocs/xamarin-docs.ru-ru/blob/live/docs/xamarin-forms/data-cloud/data/files.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by srvbpigh** [comment]
Hello, @Metalstyle
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by Metalstyle** [comment]
Вопрос решен. С автопереводчиком не обратил внимание, что надо поменять и название приложения

**Comment by CeciAc** [comment]
Здравствуйте, @Metalstyle 
Благодарим Вас за отзыв. Мы рады, что работа с нашей документацией соответствует Вашим ожиданиям. 
Надеемся получить от Вас и другие полезные отзывы, которые помогут нам улучшать работу и дальше. 
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт
