### ISSUE TITLE
Ошибка в top_menus.xml

### ISSUE THREAD

**Issue by alexeygritsenko** [MicrosoftDocs/xamarin-docs.ru-ru#16]
Вместо android:showAsAction="..." нужно использовать app:showAsAction="..." пространства имен xmlns:app="http://schemas.android.com/apk/res-auto"

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 077a373a-710a-4514-ba04-dee36309d7b3
* Version Independent ID: f8357c4d-8711-457a-3577-cce29464b51e
* Content: [Замена панели действий - Xamarin](https://docs.microsoft.com/ru-ru/xamarin/android/user-interface/controls/tool-bar/replacing-the-action-bar#feedback)
* Content Source: [docs/android/user-interface/controls/tool-bar/replacing-the-action-bar.md](https://github.com/MicrosoftDocs/xamarin-docs.ru-ru/blob/live/docs/android/user-interface/controls/tool-bar/replacing-the-action-bar.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by srvbpigh** [comment]
Hello, @alexeygritsenko
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Здравствуйте, @alexeygritsenko!  

Благодарим Вас за участие. Ваш отзыв связан с исходной документацией.  

Поэтому мы переносим Вашу заявку в репозиторий по английскому языку. Ее состояние можно просмотреть здесь: https://github.com/MicrosoftDocs/xamarin-docs/issues/2766.  

Мы очень ценим Ваш вклад в наши статьи.   

С наилучшими пожеланиями,  
Международная команда поддержки документации Майкрософт
