### ISSUE TITLE
error

### ISSUE THREAD

**Issue by andrey6719** [MicrosoftDocs/xamarin-docs.ru-ru#2]
No resource found that matches the given name (at 'icon' with value '@mipmap/icon'
в манифесте phoneword.Android ссылка на icon указывает на несуществующую папку mipmap вместо существующей папки drawable. Надо править или манифест или создавать папку mipmap и копировать туда icon. Об этом в инструкции ничего не говорится.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 2de3e72c-8948-4dd5-e37f-9cf81e62c127
* Version Independent ID: 7b7c5c7f-4102-8e91-fbe6-7d21fcc8f5be
* Content: [Краткое руководство по Xamarin.Forms - Xamarin](https://docs.microsoft.com/ru-ru/xamarin/xamarin-forms/get-started/hello-xamarin-forms/quickstart?tabs=vswin)
* Content Source: [docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs.ru-RU/blob/live/docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by gosali** [comment]
Issue moved to [MicrosoftDocs/xamarin-docs #558](https://github.com/MicrosoftDocs/xamarin-docs/issues/558) via [**ZenHub**](https://www.zenhub.com/)

**Comment by gosali** [comment]
Здравствуйте, @andrey6719 !
--
Благодарим Вас за участие. Ваш отзыв связан с исходной документацией.
Поэтому мы переносим Вашу заявку в репозиторий по английскому языку. Ее состояние можно просмотреть здесь: https://github.com/MicrosoftDocs/xamarin-docs/issues/558.

Мы очень ценим Ваш вклад в наши статьи.
С наилучшими пожеланиями,
Международная команда поддержки документации Майкрософт
