### ISSUE TITLE
TRANSLATION

### ISSUE THREAD

**Issue by equalent** [MicrosoftDocs/xamarin-docs.ru-ru#3]
Пожалуйста, дайте возможность перевести раздел UrhoSharp. Перевести Particles как частицы - это верх переводчика Bing))
andrey.turcan@hotmail.com

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 77b3902e-2721-73b8-1325-46b3cc3b1457
* Version Independent ID: b413ce33-0582-6df9-ab80-f451039a0ca8
* Content: [Использование UrhoSharp для создания трехмерных игр - Xamarin](https://docs.microsoft.com/ru-ru/xamarin/graphics-games/urhosharp/using#feedback)
* Content Source: [docs/graphics-games/urhosharp/using.md](https://github.com/MicrosoftDocs/xamarin-docs.ru-RU/blob/live/docs/graphics-games/urhosharp/using.md)
* Product: **xamarin**
* GitHub Login: @charlespetzold
* Microsoft Alias: **chape**

**Comment by LisandroSu** [comment]
Здравствуйте, @equalent ! 

Спасибо за отзыв. 

Мы активно просматриваем комментарии и скоро ответим Вам. 

С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт

**Comment by CeciAc** [comment]
Здравствуйте, @equalent! 
Спасибо за отзыв. Рассматриваемая страница переведена с использованием машинного перевода, который не всегда идеально понятен. Недавно мы добавили справа на странице функцию «Прочитать на английском», которая позволяет переключиться на английскую версию, не меняя настройки языка. 
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт
