### ISSUE TITLE
can't download iOS

### ISSUE THREAD

**Issue by kikcorp** [MicrosoftDocs/xamarin-docs.ru-ru#4]
https://fastring.xamarinliveplayer.com/ -  not working yet!!

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 79320e9a-8b52-1c24-0a5b-a7ef6a32b519
* Version Independent ID: 88548723-6f1b-50c1-163c-a9e151b024e8
* Content: [Установка Xamarin Live Player - Xamarin](https://docs.microsoft.com/ru-ru/xamarin/tools/live-player/install?tabs=ios%2Cwindows)
* Content Source: [docs/tools/live-player/install.md](https://github.com/MicrosoftDocs/xamarin-docs.ru-RU/blob/live/docs/tools/live-player/install.md)
* Product: **xamarin**
* GitHub Login: @topgenorth
* Microsoft Alias: **toopge**

**Comment by kikcorp** [comment]
Error 1016 Ray ID: 44bb23921b288fc9 • 2018-08-17 09:33:24 UTC
Origin DNS error
What happened?
You've requested a page on a website (fastring.xamarinliveplayer.com) that is on the Cloudflare network. Cloudflare is currently unable to resolve your requested domain (fastring.xamarinliveplayer.com).

**Comment by kikcorp** [comment]
How can I install this application?

**Comment by LisandroSu** [comment]
Hello, @kikcorp , 
  
Thank you for your feedback. 
  
We are actively reviewing your comments and will get back to you soon. 
 
Kind regards, 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @kikcorp ,

Thank you for your feedback.

The page this feedback refers was updated recently and the content reported is not present anymore.
If the issue persists, please open a new request.

Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button **"Give Product Feedback"** at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
