### ISSUE TITLE
problem when adding plain text

### ISSUE THREAD

**Issue by maxkalama** [MicrosoftDocs/xamarin-docs.ru-ru#5]
the sample uses Linear layout while new blank Xamarin Android project creates RelativeLayout that cause problem when dragging plain text from toolbox to the layout.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 660b0f7c-9941-2db3-63bf-fc8a97765b1e
* Version Independent ID: 5aa1e6f6-534a-05b9-c44a-1f62b24c201a
* Content: [Привет, Android: краткое руководство - Xamarin](https://docs.microsoft.com/ru-ru/xamarin/android/get-started/hello-android/hello-android-quickstart?tabs=vswin)
* Content Source: [docs/android/get-started/hello-android/hello-android-quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs.ru-RU/blob/live/docs/android/get-started/hello-android/hello-android-quickstart.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by maxkalama** [comment]
![image](https://user-images.githubusercontent.com/22190970/44466964-51710a00-a62a-11e8-8116-0e5a266f1347.png)

**Comment by maxkalama** [comment]
closed by mistake

**Comment by mgmclemore** [comment]
Hi @maxkalama, thank you for the feedback! We're in the process of updating this topic to be in sync with the new templates (which use `RelativeLayout`). The [English version](https://docs.microsoft.com/en-us/xamarin/android/get-started/hello-android/hello-android-quickstart) has been updated to `RelativeLayout` and is being translated. The associated sample app is also being updated.

**Comment by maxkalama** [comment]
Thank you, mgmclemore!
